name: inbrief
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

#------------------------------PACKAGES-------------------------------3
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.0

  # Utility Packages
  connectivity_plus: ^6.1.3

  # Icons
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  intl: ^0.20.2
  iconsax: ^0.0.8
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
  http: any
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1


  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1


  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5






  #---------------------- ./ PACKAGES END ---------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/AppIcon1.png"


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # --------------------- LOCAL ASSETS --------------------------------#

  assets:
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/placeholder/placeholder.jpg
    - assets/images/categories/
    - assets/images/content/









  # --------------------- LOCAL FONT --------------------------------#