// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKmJC82XDanPdDevLXleBSwU6xbwYoCpQ',
    appId: '1:390148591948:web:392f6da9cfa798b8c6bfe9',
    messagingSenderId: '390148591948',
    projectId: 'inbrief-cc06e',
    authDomain: 'inbrief-cc06e.firebaseapp.com',
    storageBucket: 'inbrief-cc06e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDlilKLUgZzv5RynQTwjlWWBD2m0yNMhk',
    appId: '1:390148591948:android:1eefcf9470a0ee34c6bfe9',
    messagingSenderId: '390148591948',
    projectId: 'inbrief-cc06e',
    storageBucket: 'inbrief-cc06e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzB5jt5pX4PCEgsDAPLknvLhW33dk4lGA',
    appId: '1:390148591948:ios:96097eab4de497d7c6bfe9',
    messagingSenderId: '390148591948',
    projectId: 'inbrief-cc06e',
    storageBucket: 'inbrief-cc06e.firebasestorage.app',
    iosBundleId: 'com.example.inbrief',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKmJC82XDanPdDevLXleBSwU6xbwYoCpQ',
    appId: '1:390148591948:web:eab7b5d381103eeac6bfe9',
    messagingSenderId: '390148591948',
    projectId: 'inbrief-cc06e',
    authDomain: 'inbrief-cc06e.firebaseapp.com',
    storageBucket: 'inbrief-cc06e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzB5jt5pX4PCEgsDAPLknvLhW33dk4lGA',
    appId: '1:390148591948:ios:96097eab4de497d7c6bfe9',
    messagingSenderId: '390148591948',
    projectId: 'inbrief-cc06e',
    storageBucket: 'inbrief-cc06e.firebasestorage.app',
    iosBundleId: 'com.example.inbrief',
  );

}